export const RAJ_PROFILE = {
  yearsExperience: 3,
  targetCountries: ['Ireland', 'Netherlands'],
  passiveCountries: ['UK'],
  targetRoleLane: [
    'systems analyst',
    'application analyst',
    'business systems analyst',
    'it business analyst',
    'technical business analyst',
    'uat analyst',
    'business test analyst',
    'application quality analyst',
    'payments analyst',
  ],
  targetDomains: [
    'fintech',
    'banking',
    'payments',
    'reconciliation',
    'settlement',
    'transaction',
    'kyc',
    'aml',
    'compliance',
    'risk',
    'regulatory',
    'saas finance',
    'financial services',
    'enterprise systems',
  ],
  coreSkills: [
    'sql',
    'data validation',
    'uat',
    'jira',
    'testing',
    'defect',
    'incident',
    'production support',
    'application support',
    'logs',
    'monitoring',
    'reporting',
    'workflow',
    'stakeholder',
    'requirements',
    'user stories',
  ],
  proofAssets: {
    fisFintech: 'FIS FinTech software engineering experience (banking/payments systems)',
    payGuardIE:
      'PayGuard IE - payment reconciliation, SQL validation, UAT, defect evidence portfolio project',
    regPulse:
      'RegPulse - EU FinTech regulatory readiness dashboard (DORA/PSD3/FiDA)',
    stamp4Engine: 'Stamp4 Job Positioning Intelligence Engine - internal job-fit tooling',
    autoTimeAI: 'AutoTime AI - founder, AI automation product',
  },
  positiveLocationSignals: [
    'ireland',
    'dublin',
    'cork',
    'galway',
    'limerick',
    'netherlands',
    'amsterdam',
    'rotterdam',
    'utrecht',
  ],
  permitRiskPhrases: [
    'no sponsorship',
    'must have right to work',
    'unrestricted right to work',
    'sponsorship not available',
    'must be based in ireland',
    'must already be eligible to work',
    '6 month contract',
    'contract',
    'temporary',
  ],
  salaryPermitFloorEUR: 40904,
  salaryTargetRangeEUR: { min: 45000, max: 55000 },
} as const
