import { apiCall } from './storage'

export type AtsProvider = 'greenhouse' | 'lever' | 'ashby'

export interface SponsorCompany {
  name: string
  country: 'Ireland' | 'Netherlands'
  sector: string
  whySponsorFriendly: string
  careersUrl: string
  /** Set only when the exact public ATS board token has been verified live - guessing a wrong slug just 404s. */
  atsProvider: AtsProvider | null
  atsSlug: string | null
}

/**
 * Starting point, not a verified-today register snapshot. Cross-check against the live official
 * registers before relying on a specific company: Ireland's employment permit statistics/company
 * listings (enterprise.gov.ie) and the Netherlands IND public register of recognised sponsors
 * (ind.nl/en/public-register-recognised-sponsors). Government registers change monthly.
 */
export const SPONSOR_COMPANIES: SponsorCompany[] = [
  {
    name: 'Stripe',
    country: 'Ireland',
    sector: 'Payments infrastructure',
    whySponsorFriendly: 'Large Dublin EMEA hub with a long history of Critical Skills permit sponsorship.',
    careersUrl: 'https://stripe.com/jobs/search?office_locations=Europe--Ireland--Dublin',
    atsProvider: 'greenhouse',
    atsSlug: 'stripe',
  },
  {
    name: 'Wayflyer',
    country: 'Ireland',
    sector: 'Revenue-based financing FinTech',
    whySponsorFriendly: 'Dublin-headquartered FinTech scaleup that regularly hires internationally.',
    careersUrl: 'https://wayflyer.com/en/careers',
    atsProvider: 'ashby',
    atsSlug: 'wayflyer',
  },
  {
    name: 'Fenergo',
    country: 'Ireland',
    sector: 'RegTech / client lifecycle management',
    whySponsorFriendly: 'Dublin-headquartered RegTech vendor serving global banks; frequent international hiring.',
    careersUrl: 'https://www.fenergo.com/careers',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'TransferMate',
    country: 'Ireland',
    sector: 'Cross-border payments FinTech',
    whySponsorFriendly: 'Irish-founded international payments FinTech with EU-wide hiring.',
    careersUrl: 'https://www.transfermate.com/careers',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'CurrencyFair',
    country: 'Ireland',
    sector: 'FX / cross-border payments FinTech',
    whySponsorFriendly: 'Dublin-based FX FinTech, smaller but relevant for systems/application analyst roles.',
    careersUrl: 'https://www.currencyfair.com/careers/',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'AIB (Allied Irish Banks)',
    country: 'Ireland',
    sector: 'Retail & corporate banking',
    whySponsorFriendly: 'Major Irish bank with an established international hiring and permit process.',
    careersUrl: 'https://careers.aib.ie',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Bank of Ireland',
    country: 'Ireland',
    sector: 'Retail & corporate banking',
    whySponsorFriendly: 'Major Irish bank with ongoing technology/analyst hiring.',
    careersUrl: 'https://careersbankofireland.com',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Workday',
    country: 'Ireland',
    sector: 'Enterprise finance/HR systems software',
    whySponsorFriendly: 'EMEA headquarters in Dublin; large multinational with a mature international-hire process.',
    careersUrl: 'https://workday.wd5.myworkdayjobs.com/Workday',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Deloitte Ireland',
    country: 'Ireland',
    sector: 'Financial services technology consulting',
    whySponsorFriendly: 'Big 4 firm with a large financial-services technology practice and frequent permit sponsorship.',
    careersUrl: 'https://www2.deloitte.com/ie/en/careers.html',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Accenture Ireland',
    country: 'Ireland',
    sector: 'Technology & financial services consulting',
    whySponsorFriendly: 'Large multinational consultancy with an established Irish international-hire pipeline.',
    careersUrl: 'https://www.accenture.com/ie-en/careers',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'KPMG Ireland',
    country: 'Ireland',
    sector: 'Financial services consulting',
    whySponsorFriendly: 'Big 4 firm with a large financial-services technology/risk practice and frequent permit sponsorship.',
    careersUrl: 'https://home.kpmg/ie/en/home/careers.html',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'EY Ireland',
    country: 'Ireland',
    sector: 'Financial services consulting',
    whySponsorFriendly: 'Big 4 firm with a large financial-services technology/risk practice and frequent permit sponsorship.',
    careersUrl: 'https://www.ey.com/en_ie/careers',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Citi Ireland',
    country: 'Ireland',
    sector: 'Corporate & investment banking',
    whySponsorFriendly: 'Major Dublin technology/operations hub for a global bank; frequent Critical Skills permit sponsor.',
    careersUrl: 'https://jobs.citi.com/search-jobs/Ireland',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'JPMorgan Ireland',
    country: 'Ireland',
    sector: 'Corporate & investment banking',
    whySponsorFriendly: 'Large Dublin technology and operations centre for a global bank; regular international hiring.',
    careersUrl: 'https://careers.jpmorgan.com/ie/en/students/programs/emea',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'State Street Ireland',
    country: 'Ireland',
    sector: 'Fund administration / financial services technology',
    whySponsorFriendly: 'One of Ireland’s largest financial-services employers, with ongoing systems/application analyst hiring.',
    careersUrl: 'https://www.statestreet.com/ie/en/individual/about/careers',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Northern Trust Ireland',
    country: 'Ireland',
    sector: 'Fund administration / financial services technology',
    whySponsorFriendly: 'Large Dublin/Limerick financial-services operation with regular international hiring.',
    careersUrl: 'https://careers.northerntrust.com/ireland',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Salesforce Ireland',
    country: 'Ireland',
    sector: 'Enterprise CRM/systems software',
    whySponsorFriendly: 'Large Dublin office for a major enterprise-systems vendor; frequent international hiring.',
    careersUrl: 'https://www.salesforce.com/company/careers/',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'HubSpot',
    country: 'Ireland',
    sector: 'Enterprise CRM/systems software',
    whySponsorFriendly: 'Dublin international HQ for a major CRM/systems vendor; large, active permit-sponsoring workforce.',
    careersUrl: 'https://www.hubspot.com/careers',
    atsProvider: 'greenhouse',
    atsSlug: 'hubspotjobs',
  },
  {
    name: 'Intercom',
    country: 'Ireland',
    sector: 'Customer engagement / support software',
    whySponsorFriendly: 'Dublin-founded and headquartered software company with an established international-hire pipeline.',
    careersUrl: 'https://www.intercom.com/careers/dublin',
    atsProvider: 'greenhouse',
    atsSlug: 'intercom',
  },
  {
    name: 'PayPal Ireland',
    country: 'Ireland',
    sector: 'Payments',
    whySponsorFriendly: 'Dundalk/Ballycoolin (Dublin) operations; announced a 2025 AI/fraud data-science hub adding 100 tech roles.',
    careersUrl: 'https://careers.pypl.com/locations/ireland/',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Mastercard Ireland',
    country: 'Ireland',
    sector: 'Payments',
    whySponsorFriendly: 'Dublin (Leopardstown) is Mastercard\'s European Technology Hub, growing toward 1,500+ staff.',
    careersUrl: 'https://careers.mastercard.com/us/en/dublin-ireland',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Revolut Ireland',
    country: 'Ireland',
    sector: 'Challenger bank',
    whySponsorFriendly: 'Active Dublin office with a large, ongoing hiring pipeline for a major European neobank.',
    careersUrl: 'https://www.revolut.com/en-IE/careers/',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Coinbase Ireland',
    country: 'Ireland',
    sector: 'Crypto exchange (compliance/operations hub)',
    whySponsorFriendly: 'Dublin site with a significant compliance/operations footprint - relevant for systems/application analyst roles.',
    careersUrl: 'https://www.coinbase.com/careers/positions?location=dublin',
    atsProvider: 'greenhouse',
    atsSlug: 'coinbase',
  },
  {
    name: 'Corlytics',
    country: 'Ireland',
    sector: 'RegTech (regulatory risk intelligence)',
    whySponsorFriendly: 'Dublin-headquartered RegTech vendor; one of Ireland\'s well-known regulatory-intelligence platforms.',
    careersUrl: 'https://www.corlytics.com/company/careers/',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'AQMetrics',
    country: 'Ireland',
    sector: 'RegTech (regulatory reporting)',
    whySponsorFriendly: 'Irish RegTech vendor for regulatory reporting; hires across Ireland, France, Luxembourg and the UK.',
    careersUrl: 'https://ie.linkedin.com/company/aqmetrics',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Google Ireland',
    country: 'Ireland',
    sector: 'Big Tech (EMEA HQ)',
    whySponsorFriendly: 'Dublin EMEA headquarters; one of the highest-volume Irish employment permit sponsors.',
    careersUrl: 'https://www.google.com/about/careers/applications/jobs/results/?location=Dublin',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Meta Ireland',
    country: 'Ireland',
    sector: 'Big Tech (EMEA HQ)',
    whySponsorFriendly: 'Dublin EMEA headquarters with a long-standing history of international permit sponsorship.',
    careersUrl: 'https://www.metacareers.com/locations/dublin/',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Microsoft Ireland',
    country: 'Ireland',
    sector: 'Big Tech / cloud (EMEA operations centre)',
    whySponsorFriendly: 'Large Dublin EMEA operations centre; frequent international hiring and permit sponsorship.',
    careersUrl: 'https://jobs.careers.microsoft.com/global/en/search?lc=Dublin%2C%20Ireland',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Amazon Ireland',
    country: 'Ireland',
    sector: 'Big Tech / cloud',
    whySponsorFriendly: 'Large Dublin workforce across engineering and operations; regular international hiring.',
    careersUrl: 'https://www.amazon.jobs/en/locations/dublin-ireland',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'LinkedIn Ireland',
    country: 'Ireland',
    sector: 'Big Tech (EMEA HQ)',
    whySponsorFriendly: 'Dublin EMEA headquarters with an established international-hire pipeline.',
    careersUrl: 'https://careers.linkedin.com/locations/dublin',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Adyen',
    country: 'Netherlands',
    sector: 'Global payments platform',
    whySponsorFriendly: 'Amsterdam-headquartered global payments company with a large Highly Skilled Migrant intake.',
    careersUrl: 'https://careers.adyen.com',
    atsProvider: 'greenhouse',
    atsSlug: 'adyen',
  },
  {
    name: 'Mollie',
    country: 'Netherlands',
    sector: 'Payments FinTech',
    whySponsorFriendly: 'Amsterdam-based payments FinTech serving 250,000+ merchants; regularly hires internationally.',
    careersUrl: 'https://jobs.mollie.com',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Bunq',
    country: 'Netherlands',
    sector: 'Challenger bank',
    whySponsorFriendly: 'Dutch neobank with a young, internationally hired workforce.',
    careersUrl: 'https://www.bunq.com/careers',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'ING',
    country: 'Netherlands',
    sector: 'Retail & corporate banking',
    whySponsorFriendly: 'Major Dutch bank with an established Highly Skilled Migrant sponsorship process.',
    careersUrl: 'https://www.ing.jobs',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Backbase',
    country: 'Netherlands',
    sector: 'Digital banking platform software',
    whySponsorFriendly: 'Amsterdam-headquartered banking-software vendor selling to global banks; internationally hires engineering/analyst roles.',
    careersUrl: 'https://www.backbase.com/careers',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Booking.com',
    country: 'Netherlands',
    sector: 'Travel platform (large finance/data systems function)',
    whySponsorFriendly: 'Very large Amsterdam employer with one of the highest Highly Skilled Migrant sponsorship volumes in NL.',
    careersUrl: 'https://careers.booking.com',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Databricks',
    country: 'Netherlands',
    sector: 'Data/analytics platform',
    whySponsorFriendly: 'Active Amsterdam-area presence and a regular Highly Skilled Migrant sponsor for data/platform roles.',
    careersUrl: 'https://www.databricks.com/company/careers/open-positions',
    atsProvider: 'greenhouse',
    atsSlug: 'databricks',
  },
  {
    name: 'Uber Netherlands',
    country: 'Netherlands',
    sector: 'Platform / payments-adjacent operations',
    whySponsorFriendly: 'Amsterdam EMEA hub with ongoing operations, risk and systems-analyst-style hiring.',
    careersUrl: 'https://www.uber.com/careers/list/?location=Netherlands',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'TomTom',
    country: 'Netherlands',
    sector: 'Location technology',
    whySponsorFriendly: 'Amsterdam-headquartered technology company with an established international-hire pipeline.',
    careersUrl: 'https://www.tomtom.com/careers/',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Elastic',
    country: 'Netherlands',
    sector: 'Data/search platform software',
    whySponsorFriendly: 'Co-founded in the Netherlands with an ongoing Amsterdam-area presence and international hiring.',
    careersUrl: 'https://www.elastic.co/careers',
    atsProvider: 'greenhouse',
    atsSlug: 'elastic',
  },
  {
    name: 'Optiver',
    country: 'Netherlands',
    sector: 'Trading / market making',
    whySponsorFriendly: 'Large Amsterdam-headquartered trading firm with a long history of international hiring.',
    careersUrl: 'https://optiver.com/working-at-optiver/career-opportunities/',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Mambu',
    country: 'Netherlands',
    sector: 'Core banking SaaS platform',
    whySponsorFriendly: 'Amsterdam-headquartered core-banking software vendor serving 260+ banks/lenders/fintechs across 65 countries.',
    careersUrl: 'https://mambu.com/en/careers',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Just Eat Takeaway.com',
    country: 'Netherlands',
    sector: 'Platform / payments-adjacent operations',
    whySponsorFriendly: 'Amsterdam-headquartered platform company with an established international-hire pipeline.',
    careersUrl: 'https://careers.justeattakeaway.com',
    atsProvider: null,
    atsSlug: null,
  },
  {
    name: 'Philips',
    country: 'Netherlands',
    sector: 'Health technology (large enterprise systems function)',
    whySponsorFriendly: 'Major Dutch multinational headquartered in the Amsterdam area; long-standing international hiring.',
    careersUrl: 'https://www.careers.philips.com',
    atsProvider: null,
    atsSlug: null,
  },
]

export function sponsorRegisterLinks() {
  return {
    ireland: 'https://enterprise.gov.ie/en/what-we-do/workplace-and-skills/employment-permits/statistics/',
    netherlands: 'https://ind.nl/en/public-register-recognised-sponsors/public-register-work',
  }
}

export async function getCustomSponsorCompanies(): Promise<SponsorCompany[]> {
  return apiCall<SponsorCompany[]>('sponsor-companies', { method: 'GET' })
}

export async function addCustomSponsorCompany(company: SponsorCompany): Promise<void> {
  await apiCall<{ ok: true }>('sponsor-companies', { method: 'POST', body: JSON.stringify(company) })
}

export async function getAllSponsorCompanies(): Promise<SponsorCompany[]> {
  return [...SPONSOR_COMPANIES, ...(await getCustomSponsorCompanies())]
}
