import { EMPTY_APPLICATION_PACK } from './generator'
import type { TrackedJob, TrackerStatus } from './types'

const STATUSES: TrackerStatus[]=['Saved','Qualified','Contacted','Applied','Follow-up','Recruiter Screen','Interview','Final Stage','Offer','Rejected','Archived']
function cells(line:string){const out:string[]=[];let value='';let quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&quoted&&line[i+1]==='"'){value+='"';i++}else if(ch==='"')quoted=!quoted;else if(ch===','&&!quoted){out.push(value.trim());value=''}else value+=ch}out.push(value.trim());return out}
function country(value:string){const v=value.trim().toLowerCase();if(['ie','irl','ireland'].includes(v))return'Ireland';if(['nl','nld','netherlands','holland'].includes(v))return'Netherlands';if(['de','deu','germany'].includes(v))return'Germany';return value.trim()||'EU / unclear'}
export function importKey(job:Pick<TrackedJob,'company'|'roleTitle'|'country'>){return`${job.company}|${job.roleTitle}|${job.country}`.toLowerCase().replace(/\s+/g,' ').trim()}
function make(row:Record<string,string>,index:number):TrackedJob|null{const company=row.company?.trim();const roleTitle=(row['role title']||row.role||row.title)?.trim();if(!company||!roleTitle)return null;const status=STATUSES.includes(row.status as TrackerStatus)?row.status as TrackerStatus:'Saved';const score=Math.max(0,Math.min(5,Number(row.score)||0));return{id:`import-${Date.now()}-${index}-${company}-${roleTitle}`.replace(/[^a-zA-Z0-9-]/g,'-').slice(0,190),company,roleTitle,country:country(row.country||''),location:row.location||'',salary:row.salary||null,score,decision:score>=4?'Apply Now':score>=3?'Apply with Proof Fix':'Save / Low Priority',status,dateAdded:row['date added']||row.date||new Date().toISOString(),applicationUrl:row['application url']||row.url||undefined,applicationDeadline:row.deadline||undefined,sponsorshipStatus:'Unknown',sponsorshipEvidence:'',notes:row.notes||'',generatedPack:EMPTY_APPLICATION_PACK,proofMap:[],correctionActions:[]}}
export function parseTrackerImport(text:string,filename:string):TrackedJob[]{if(filename.toLowerCase().endsWith('.json')){const parsed=JSON.parse(text) as unknown;const rows=Array.isArray(parsed)?parsed:(parsed&&typeof parsed==='object'&&Array.isArray((parsed as {trackedJobs?:unknown[]}).trackedJobs)?(parsed as {trackedJobs:unknown[]}).trackedJobs:[]);return rows.filter((v):v is TrackedJob=>Boolean(v&&typeof v==='object'&&'company'in v&&'roleTitle'in v))}const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2)return[];const headers=cells(lines[0]).map(v=>v.toLowerCase());return lines.slice(1).map((line,index)=>make(Object.fromEntries(cells(line).map((v,i)=>[headers[i],v])),index)).filter((v):v is TrackedJob=>Boolean(v))}
export function dedupeImports(incoming:TrackedJob[],existing:TrackedJob[]){const seen=new Set(existing.map(importKey));const unique:TrackedJob[]=[];let duplicates=0;for(const job of incoming){const key=importKey(job);if(seen.has(key)){duplicates++;continue}seen.add(key);unique.push(job)}return{unique,duplicates}}